name: MolSim CI Build

on:
  push:
    branches:
      - dev-sheet_4
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libxerces-c-dev

    - name: Create build directory
      run: | 
          mkdir build
          cd build

    - name: Run CMake and Address Sanitizer
      run: cmake -S . -B build -DCMAKE_CXX_FLAGS="-fsanitize=address -g"

    - name: Build with Make
      run: cmake --build build

    - name: Build and run Google Tests
      run: |
        cd build
        ctest --output-on-failure
