name: MolSim CI Build

on:
  push:
    branches:
      - dev-sheet_2-task_2
  pull_request:
    branches:
      - dev-sheet_2
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install CMake
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libxerces-c-dev

    # Step 3: Create build directory
    - name: Create build directory
      run: mkdir -p build

    # Step 4: Run CMake to configure the project
    - name: Run CMake and Address Sanitizer
      run: cmake -S . -B build -DCMAKE_CXX_FLAGS="-fsanitize=address -g"

    # Step 5: Build the project
    - name: Build with Make
      run: cmake --build build

    # Step 6
    - name: Build and run Google Tests
      run: |
        cmake -S tests -B build/tests
        cmake --build build/tests
        cd build/tests
        ctest --output-on-failure
